# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Noemi Glaeser
  de: Noemi Gläser
  it: Noemi Glaeser
email: firstinitial lastname AT umd DOT edu
description:
  en: Personal Website
  de: 
  it: 
index:
  en:
  de: de
  it: it
feed:
  en: /feed.xml
  de: /feed-de.xml
  it: /feed-it.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
linkedin_username: nglaeser
github_username:  nglaeser
keybase_username: nglaeser
orcid: 0000-0002-6464-2534

# Build settings
markdown: kramdown
mathjax: true
theme: minima

# theme: jekyll-theme-minimal
